load(
    "@rules_scala//scala:scala.bzl",
    "scala_binary",
    "scala_library",
    "scala_test",
)

# DAY 01
scala_library(
    name = "day01scala",
    srcs = ["Day01.scala"],
    deps = [
    ],
)

scala_binary(
    name = "day01scala_main",
    srcs = ["Day01Main.scala"],
    main_class = "year2025.day01.main",
    deps = [
        ":day01scala",
    ],
)

scala_test(
    name = "day01scala_test",
    srcs = ["Day01Test.scala"],
    deps = [
        ":day01scala",
        "@maven//:org_scalacheck_scalacheck_3",
        "@maven//:org_scalatestplus_scalacheck_1_18_3",
    ],
)

# DAY 02
scala_library(
    name = "day02scala",
    srcs = ["Day02.scala"],
    deps = [
    ],
)

scala_binary(
    name = "day02scala_main",
    srcs = ["Day02Main.scala"],
    main_class = "year2025.day02.main",
    deps = [
        ":day02scala",
    ],
)

scala_test(
    name = "day02scala_test",
    srcs = ["Day02Test.scala"],
    deps = [
        ":day02scala",
        "@maven//:org_scalacheck_scalacheck_3",
        "@maven//:org_scalatestplus_scalacheck_1_18_3",
    ],
)

# DAY 03
scala_library(
    name = "day03scala",
    srcs = ["Day03.scala"],
    deps = [
    ],
)

scala_binary(
    name = "day03scala_main",
    srcs = ["Day03Main.scala"],
    main_class = "year2025.day03.main",
    deps = [
        ":day03scala",
    ],
)

scala_test(
    name = "day03scala_test",
    srcs = ["Day03Test.scala"],
    deps = [
        ":day03scala",
        "@maven//:org_scalacheck_scalacheck_3",
        "@maven//:org_scalatestplus_scalacheck_1_18_3",
    ],
)

# DAY 04
scala_library(
    name = "day04scala",
    srcs = ["Day04.scala"],
    deps = [
    ],
)

scala_binary(
    name = "day04scala_main",
    srcs = ["Day04Main.scala"],
    main_class = "year2025.day04.main",
    deps = [
        ":day04scala",
    ],
)

scala_test(
    name = "day04scala_test",
    srcs = ["Day04Test.scala"],
    deps = [
        ":day04scala",
        "@maven//:org_scalacheck_scalacheck_3",
        "@maven//:org_scalatestplus_scalacheck_1_18_3",
    ],
)
