package year2025
package day07

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import org.scalatestplus.scalacheck.ScalaCheckPropertyChecks
import org.scalacheck.Gen

class Day07Spec extends AnyFlatSpec with Matchers with ScalaCheckPropertyChecks:

  // it should "pass the examples in the part ONE problem descrition" in:
  //   val input: Iterator[String] = 
  //     """|.......S.......
  //        |...............
  //        |.......^.......
  //        |...............
  //        |......^.^......
  //        |...............
  //        |.....^.^.^.....
  //        |...............
  //        |....^.^...^....
  //        |...............
  //        |...^.^...^.^...
  //        |...............
  //        |..^...^.....^..
  //        |...............
  //        |.^.^.^.^.^...^.
  //        |...............""".stripMargin.split('\n').iterator
  //   val grid = input.parse
  //   (grid.cascadeRays(Set(grid.startPoint))) should equal (21)


  it should "pass the examples in the part TWO problem descrition" in:
    val input: Iterator[String] = 
      """|.......S.......
         |...............
         |.......^.......
         |...............
         |......^.^......
         |...............
         |.....^.^.^.....
         |...............
         |....^.^...^....
         |...............
         |...^.^...^.^...
         |...............
         |..^...^.....^..
         |...............
         |.^.^.^.^.^...^.
         |...............""".stripMargin.split('\n').iterator
    val grid = input.parse
    grid.countTimelines should equal (40L)